version: '3'

services:
  app:
    build: .
    ports:
      - 443:443
    volumes:
      - .:/var/www/app
      - ./server.crt:/etc/apache2/ssl/server.crt
      - ./server.key:/etc/apache2/ssl/server.key

    working_dir: /var/www/app
